version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: lawgic_user
      POSTGRES_PASSWORD: lawgicpass
      POSTGRES_DB: lawgic
    ports:
      - "5432:5432"
  backend:
    build: .
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql+asyncpg://lawgic_user:lawgicpass@db/lawgic
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
    ports:
      - "8000:8000"